#!/usr/bin/env sh -u

curl -H "Accept: application/vnd.github.mercy-preview+json" \
     https://api.github.com/users/nerevu/repos?per_page=100 \
     | jq . > data/nerevu-repos.json

curl -H "Accept: application/vnd.github.mercy-preview+json" \
     https://api.github.com/users/reubano/repos?per_page=100 \
     | jq . > data/reubano-repos.json

curl -d "method=flickr.photosets.getPhotos" \
     -d "api_key=${FLICKR_ACCOUNT_KEY}" \
     -d "user_id=47144176@N00" \
     -d "extras=description,date_upload,date_taken,original_format,o_dims,media,url_o" \
     -d "format=json" \
     -d "nojsoncallback=1" \
     -d "photoset_id=72157676561966910" \
     https://api.flickr.com/services/rest \
     | jq . > data/post-images-gallery.json
